apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-demo
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-demo
  template:
    metadata:
      labels:
        app: redis-demo
    spec:
      containers:
        - name: redis-demo
          image: 856727815121.dkr.ecr.us-east-1.amazonaws.com/kafka-consumer:latest
          ports:
            - containerPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: redis-demo
  namespace: redis
spec:
  selector:
    app: redis-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: LoadBalancer